spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jonathandavidv09@gmail.com
spring.mail.password=gyxr sdkg zigz svwi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Spring Boot Logging (optional)
logging.level.org.springframework=INFO
